In [2]:
import tensorflow as tf
import tensorflow.io as ti
import tensorflow.train as tt
import tensorflow.keras as kras
data_path='/Users/ijeonghun/Documents/projects/dacon/웹광고/train.csv'

In [3]:
with open(data_path,"r") as f:
    data=f.readlines()
data_size=len(data)-1 # 헤더 제거

In [4]:
print('데이터셋 사이즈 : ',len(data)-1)

데이터셋 사이즈 :  28605391


# 방법 1.
make_csv_dataset

In [33]:
import functools as ft
fix_params={'file_pattern':[data_path],"ignore_errors":True,"shuffle":False}
tf_dataset=ft.partial(tf.data.experimental.make_csv_dataset,**fix_params)

In [34]:
Dataset=tf_dataset(batch_size=1)

In [35]:
test=Dataset.map(lambda x:x["ID"])

In [36]:
for x in Dataset.take(6):
    print(x)

OrderedDict({'ID': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'TRAIN_00000000'], dtype=object)>, 'Click': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 'F01': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'NSLHFNS'], dtype=object)>, 'F02': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'AVKQTCL'], dtype=object)>, 'F03': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'DTZFPRW'], dtype=object)>, 'F04': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([114.], dtype=float32)>, 'F05': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'ISVXFVA'], dtype=object)>, 'F06': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 'F07': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'PQZBVMG'], dtype=object)>, 'F08': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'LPYPUNA'], dtype=object)>, 'F09': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'IZYJZDA'], dtype=object)>, 'F10': <tf.Tensor: shape=(1,), dtype=string, num

2024-05-24 19:28:16.502381: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


tf.string

In [1]:
for x in Dataset.take(6):
    print(x)

NameError: name 'Dataset' is not defined

In [10]:
# shuffle_params={"buffer_size":data_size//7,"seed":10}
# Dataset=Dataset.repeat(3).shuffle(**shuffle_params).batch(data_size//7)

In [11]:
test_data=Dataset.take(1)

In [13]:
for x in test_data:
    print(x)

2024-05-24 19:16:25.198534: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:19: Filling up shuffle buffer (this may take a while): 362723 of 4086484
2024-05-24 19:16:35.198583: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:19: Filling up shuffle buffer (this may take a while): 723394 of 4086484
2024-05-24 19:16:55.198583: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:19: Filling up shuffle buffer (this may take a while): 1480632 of 4086484


# 방법 2.
CsvDataset

나중에 사용

In [28]:
import pandas as pd
import numpy as np
dtype=pd.read_csv(data_path,nrows=100).dropna(axis=0).dtypes

살펴보자

In [7]:
Datase

<_PrefetchDataset element_spec=OrderedDict({'ID': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'Click': TensorSpec(shape=(1,), dtype=tf.int32, name=None), 'F01': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F02': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F03': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F04': TensorSpec(shape=(1,), dtype=tf.float32, name=None), 'F05': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F06': TensorSpec(shape=(1,), dtype=tf.int32, name=None), 'F07': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F08': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F09': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F10': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F11': TensorSpec(shape=(1,), dtype=tf.float32, name=None), 'F12': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F13': TensorSpec(shape=(1,), dtype=tf.string, name=None), 'F14': TensorSpec(shape=(1,), dtype=tf.int32, name=None), 'F15': Tenso

튜플 분리

In [7]:
str_tuple=[x for x,y in dataset.element_spec.items() if y.dtype==tf.string]
str_tuple.remove("ID")
int_tuple=[x for x,y in dataset.element_spec.items() if y.dtype==tf.int32]
float_tuple=[x for x,y in dataset.element_spec.items() if y.dtype==tf.float32]

In [8]:
# str_tuple 처리 -> ID 튜플은 사용허지 않음
str_input_shape,int_input_shape,float_input_shape=[len(str_tuple),],[len(int_tuple),],[len(float_tuple),]

In [13]:
str_input=dataset.map(lambda x:{tup:x[tup] for tup in str_tuple})
int_input=dataset.map(lambda x:{tup:x[tup] for tup in int_tuple})
float_input=dataset.map(lambda x:{tup:x[tup] for tup in float_tuple})

In [23]:
int_test_df=int_input.take(1).as_numpy_iterator()

In [24]:
for i in int_test_df:
    print(i)

{'Click': array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32), 'F06': array([   2,    0,    1,    0,  126,   35,   40,    2,    0,   -1,   84,
         28,    5,    0,   41,    1,   -1,   -1,    0,  106,   52,   32,
         64,    4,    2,  562,   33,  220,   10,    2,    1,   12,   11,
         -1,    2,    6,   -1,    1,   -1,   19,   83,  223,  203,    0,
          2,    1,    3,    1,   36,    8,  393,   16,    3, 1087,    1,
         34,    3,   -1,    1,    1,  119,   16,    0,   16,   10,   64,
        132,   48,   37,   25,    3,    7,   -1,    2,  263,    0,    0,
          0,    1,   46,    1, 

2024-05-22 15:18:04.171870: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [25]:
dataset.filter(map(lambda x:x.))

SyntaxError: invalid syntax (4143651624.py, line 1)

In [78]:
for i in dataset.take(1):
    tf.data.Dataset.sample_from_datasets()

tf.Tensor(
[b'TRAIN_00008460' b'TRAIN_00000837' b'TRAIN_00007589' b'TRAIN_00001842'
 b'TRAIN_00007032' b'TRAIN_00004418' b'TRAIN_00006119' b'TRAIN_00006769'
 b'TRAIN_00008766' b'TRAIN_00002984' b'TRAIN_00001229' b'TRAIN_00001935'
 b'TRAIN_00002897' b'TRAIN_00007692' b'TRAIN_00002356' b'TRAIN_00002666'
 b'TRAIN_00007459' b'TRAIN_00007885' b'TRAIN_00000997' b'TRAIN_00003755'
 b'TRAIN_00007990' b'TRAIN_00000477' b'TRAIN_00001261' b'TRAIN_00001111'
 b'TRAIN_00005896' b'TRAIN_00007800' b'TRAIN_00006966' b'TRAIN_00007457'
 b'TRAIN_00004908' b'TRAIN_00009926' b'TRAIN_00005651' b'TRAIN_00006417'
 b'TRAIN_00006027' b'TRAIN_00007410' b'TRAIN_00009217' b'TRAIN_00001505'
 b'TRAIN_00009707' b'TRAIN_00002139' b'TRAIN_00001960' b'TRAIN_00006440'
 b'TRAIN_00002975' b'TRAIN_00002061' b'TRAIN_00000657' b'TRAIN_00006950'
 b'TRAIN_00003172' b'TRAIN_00002598' b'TRAIN_00002595' b'TRAIN_00006547'
 b'TRAIN_00002591' b'TRAIN_00009160' b'TRAIN_00001933' b'TRAIN_00008059'
 b'TRAIN_00005451' b'TRAIN_00001458' b'T

2024-05-17 17:56:37.085696: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
